[tool.poetry]
name = "log-enricher"
version = "0.1.4"
description = "Library to enrich structured logs"
authors = ["Arni Inaba Kjartansson <arni@grid.is>"]
license = "MIT"
repository = "https://github.com/arni-inaba/log-enricher"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
python-json-logger = "^0.1.11"
strenum = "^0.4.0"
sorcery = "^0.2.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
freezegun = "^0.3.12"
mypy = {version = "=0.720.0", allows-prereleases = true}
flake8 = "^3.7"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
